# global config
global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'network'
    static_configs:
      - targets: 
        - 192.168.16.1
        - 192.168.99.1
        - 192.168.99.2
        - 192.168.99.4
        - 192.168.99.5
        - 192.168.99.6
        - 192.168.99.254
    metrics_path: /snmp
    params:
      module: [nec]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116
  - job_name: 'srv_node'
    static_configs:
      - targets: 
        - 192.168.99.99:9090
        - 192.168.99.100:9090
  - job_name: 'vj_system'
    static_configs:
      - targets: 
        - 192.168.20.100:9182
  - job_name: 'ndi_system'
    static_configs:
      - targets: 
        - 192.168.20.201:9090
        - 192.168.20.202:9090
        - 192.168.20.203:9090
